version: '3.7'

services:

  frontend:
    restart: always
    container_name: frontend
    env_file:
      - ./frontend/.env
    build:
      context: ./frontend
    ports:
      - 8080:8080
    expose:
      - 8080

  backend:
    restart: always
    container_name: backend
    build:
      context: ./
    ports:
      - "8081:8081"
    expose:
      - 8081

#  db:
#    container_name: db
#    env_file:
#      - .env
#    build: ./database
#    restart: always
#    ports:
#      - 5432:5432
#    volumes:
#      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
